### ISSUE TITLE
Archive this repo in favor of golang-jwt/jwt ?

### ISSUE THREAD

**Issue by corny** [form3tech-oss/jwt-go#15]
It might be confusing for many people if there is more than one actively maintained fork of https://github.com/dgrijalva/jwt-go
What do you (maintainers) think of archiving this repository in favor of https://github.com/golang-jwt/jwt on focussing the effort on a single repository?

**Comment by joshua-hill-form3** [comment]
We agree 👍🏻 This repo is now archived.
