### ISSUE TITLE
aud not handling a string vs. 

### ISSUE THREAD

**Issue by jaysonhurd** [form3tech-oss/jwt-go#5]
https://tools.ietf.org/html/rfc7519#section-4.1.3

RFC above says this should support a string or an array of strings but currently it only supports an array of strings in this package.

The repo you forked from appears to have started this in an unreleased version here:

https://github.com/dgrijalva/jwt-go/blob/v4.0.0-preview1/claim_strings.go

We're running into an issue with Azure tokens not being able to validate because aud returns from it as just a string and not an array of strings.  Before going on to fix this ourselves we thought to see if it's something you wanted to fix here rather than have another repo out there doing the same thing.

**Comment by Fenny** [comment]
@Waterdrips, @martinreus-form3 could we fix this on this fork?

**Comment by Waterdrips** [comment]
Hey, got an example payload? 

Thought this was a test for a single string audience here:
https://github.com/form3tech-oss/jwt-go/blob/master/map_claims_test.go#L16-L26

**Comment by jaysonhurd** [comment]
Thanks!  We will test it out.

**Comment by joshua-hill-form3** [comment]
This fork is now archived.
