### ISSUE TITLE
Issue validating Audience due to type problem

### ISSUE THREAD

**Issue by MJoeWatson** [form3tech-oss/jwt-go#7]
First, thanks for this module update. It's appreciated! 

However I've encountered an issue when trying to verify the audience. I'm getting a type error (`interface conversion: interface {} is []interface {}, not []string`) and not entirely sure where I am going wrong.

```
jwtMiddleware := jwtmiddleware.New(jwtmiddleware.Options {
    ValidationKeyGetter: func(token *jwt.Token) (interface{}, error) {
        aud := "https://xxxx.xxxx.xxx"
        checkAud := token.Claims.(jwt.MapClaims).VerifyAudience(aud, false)
```

```
func (m MapClaims) VerifyAudience(cmp string, req bool) bool {
        aud, ok := m["aud"].([]string)
```

This check fails as it is not of type []string. Is this to do with how the jwt.Token is configured or something outside of the modules control?

Thanks in advance

**Comment by gregmillz** [comment]
I'm using this for now until someone recommends something else:

```
 aud := token.Claims.(jwt.MapClaims)["aud"].([]interface{})                                                                  
                                                                                                                             
 s := make([]string, len(aud)) // https://stackoverflow.com/questions/44027826/convert-interface-to-string-in-golang                                                                                   
 for i, v := range aud {                                                                                                     
     s[i] = fmt.Sprint(v)                                                                                                    
 }                                                                                                                           
 token.Claims.(jwt.MapClaims)["aud"] = s                                                                                     
                                                                                                                             
 checkAud := token.Claims.(jwt.MapClaims).VerifyAudience(auth0.Audience, false)                                              
 if !checkAud {                                                                                                              
     return token, errors.New("Invalid audience")                                                                            
 }          
```

**Comment by grounded042** [comment]
This is most likely because the token is parsed JSON and my guess is that aud is coming through as `[]interface{}`.

**Comment by andrewalexander** [comment]
confirmed that this is happening for me as well. Not sure the cause, but modifying `VerifyAudience` with a quick and dirty hack seemed to make it happy in a local `vendor/`. Will likely just do what @truescotian has done in the meantime, which seems like a cleaner version of my hack.

```
func (m MapClaims) VerifyAudience(cmp string, req bool) bool {
	//aud, ok := m["aud"].([]string)
	var aud []string
	sts, ok := m["aud"].([]interface{})
	if !ok {
		strAud, ok := m["aud"].(string)
		if !ok {
			return false
		}
		aud = append(aud, strAud)
	} else {
		for _, a := range sts {
			aud = append(aud, a.(string))
		}
	}

	return verifyAud(aud, cmp, req)
}
```

**Comment by aaronprice00** [comment]
Finally have a working version and can contribute to this conversation. 

[]interface{} looks like it was planned to be phased out or kept for backwards compatibility.  
By default jwt.Parse calls jwt.ParseWithClaims and passes in MapClaims{} which is of type map[string]interface{}
Take a look at: https://github.com/form3tech-oss/jwt-go/blob/master/MIGRATION_GUIDE.md
But you can instead use ParseWithClaims with custom or StandardClaims and have direct access to claims.Audience (type []string) much nicer and supported by VerifyAudience!  

`
	// Now parse the token

	parsedToken, err := jwt.ParseWithClaims(token, &MyClaims{}, m.Options.ValidationKeyGetter)

	// Broken implementation:
	// parsedToken, err := jwt.Parse(token, m.Options.ValidationKeyGetter)
`

Default functionality is definitely broken but maybe time to move on? 
So this is part of a larger conversation about Auth0 documentation, I'll clean up my code and provide a repo for reference.

**Comment by chrisk314** [comment]
@aaronprice00 how are you getting this to work? I'm trying the exact same approach that you mention as far as I can tell and the type issue for `Audience` is still a problem.

Here's my claims struct

```
type JwtCustomClaims struct {
	Permissions []string `json:"permissions"`
	*jwt.StandardClaims
}
```

Then I call `ParseWithClaims` like so

```
parsedToken, err := jwt.ParseWithClaims(token, &JwtCustomClaims{}, jh.Options.ValidationKeyGetter)
```

Which results in the error

```
json: cannot unmarshal string into Go struct field JwtCustomClaims.aud of type []string
```

So not sure what I'm doing wrong here or what you're doing differently but certainly doesn't seem to be working on my end.

**Comment by aaronprice00** [comment]
@chrisk314   hmm not seeing the problem on first sight. 
Also, lets move implementation conversation over to auth0/go-jwt-middleware
I posted my full solution: https://github.com/auth0/go-jwt-middleware/issues/72

**Comment by ah-f3** [comment]
https://github.com/form3tech-oss/jwt-go/releases/tag/v3.2.3 there is a new release to check for []interface type
